#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUST_REPO="$ROOT_DIR/repos/scripting-engine-rust"
UNITY_PKG="$ROOT_DIR/repos/scripting-engine-unity"

PROFILE="release"
TARGET=""

usage() {
  cat <<USAGE
Usage: $(basename "$0") [--profile debug|release] [--target <triple>]

Builds scripting engine FFI and copies it to the canonical Unity plugin path.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)
      PROFILE="$2"; shift 2 ;;
    --target)
      TARGET="$2"; shift 2 ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      echo "Unknown arg: $1" >&2
      usage
      exit 1 ;;
  esac
done

if [[ "$PROFILE" != "debug" && "$PROFILE" != "release" ]]; then
  echo "Invalid profile: $PROFILE" >&2
  exit 1
fi

if [[ -z "$TARGET" ]]; then
  TARGET="$(rustc -vV | sed -n 's/^host: //p')"
fi

platform_for_target() {
  local t="$1"
  case "$t" in
    *windows*) echo "Windows" ;;
    *linux*) echo "Linux" ;;
    *apple-darwin*) echo "macOS" ;;
    *) echo "" ;;
  esac
}

arch_for_target() {
  local t="$1"
  local arch="${t%%-*}"
  case "$arch" in
    x86_64) echo "x86_64" ;;
    aarch64|arm64) echo "arm64" ;;
    *) echo "$arch" ;;
  esac
}

ext_for_target() {
  local t="$1"
  case "$t" in
    *windows*) echo "dll" ;;
    *linux*) echo "so" ;;
    *apple-darwin*) echo "dylib" ;;
    *) echo "" ;;
  esac
}

prefix_for_target() {
  local t="$1"
  case "$t" in
    *windows*) echo "" ;;
    *) echo "lib" ;;
  esac
}

remove_legacy_runtime_artifacts() {
  local plugins_root="$UNITY_PKG/Runtime/Plugins"
  local canonical_windows="$plugins_root/Windows/x86_64/se_ffi.dll"
  local canonical_linux="$plugins_root/Linux/x86_64/libse_ffi.so"

  rm -rf "$plugins_root/Windows/x86_64/Debug" "$plugins_root/Windows/x86_64/Debug.meta"

  while IFS= read -r runtime_file; do
    [[ -z "$runtime_file" ]] && continue
    if [[ "$runtime_file" != "$canonical_windows" && "$runtime_file" != "$canonical_linux" ]]; then
      echo "Removing legacy runtime binary: $runtime_file"
      rm -f "$runtime_file" "$runtime_file.meta"
    fi
  done < <(find "$plugins_root" -type f \( -name "se_ffi.dll" -o -name "libse_ffi.so" \))
}

if [[ ! -d "$RUST_REPO" ]]; then
  echo "Missing repo: $RUST_REPO" >&2
  exit 1
fi
if [[ ! -d "$UNITY_PKG" ]]; then
  echo "Missing repo: $UNITY_PKG" >&2
  exit 1
fi

PLATFORM="$(platform_for_target "$TARGET")"
ARCH="$(arch_for_target "$TARGET")"
EXT="$(ext_for_target "$TARGET")"
PREFIX="$(prefix_for_target "$TARGET")"
if [[ -z "$PLATFORM" || -z "$EXT" ]]; then
  echo "Unsupported target: $TARGET" >&2
  exit 1
fi

TARGET_DIR="$(cd "$RUST_REPO" && cargo metadata --format-version 1 --no-deps | sed -n 's/.*"target_directory":"\([^"]*\)".*/\1/p' | head -n 1)"
if [[ -z "$TARGET_DIR" ]]; then
  echo "Failed to resolve cargo target_directory" >&2
  exit 1
fi

CARGO_ARGS=(build -p se-ffi --target "$TARGET")
if [[ "$PROFILE" == "release" ]]; then
  CARGO_ARGS+=(--release)
fi

(cd "$RUST_REPO" && cargo "${CARGO_ARGS[@]}")

OUT_PATH="$TARGET_DIR/$TARGET/$PROFILE/${PREFIX}se_ffi.$EXT"
if [[ ! -f "$OUT_PATH" ]]; then
  echo "Missing output: $OUT_PATH" >&2
  exit 1
fi

remove_legacy_runtime_artifacts

DEST_DIR="$UNITY_PKG/Runtime/Plugins/$PLATFORM/$ARCH"
mkdir -p "$DEST_DIR"
cp "$OUT_PATH" "$DEST_DIR/"

SE_PKGID="$(cd "$RUST_REPO" && cargo pkgid -p se-ffi)"
SE_VERSION="${SE_PKGID##*@}"
if [[ "$SE_VERSION" == "$SE_PKGID" ]]; then
  SE_VERSION="${SE_PKGID##*#}"
fi
GIT_SHORT_SHA="$(cd "$RUST_REPO" && git rev-parse --short=12 HEAD)"
if [[ -z "$SE_VERSION" || -z "$GIT_SHORT_SHA" ]]; then
  echo "Failed to resolve runtime build id components (version='$SE_VERSION' sha='$GIT_SHORT_SHA')" >&2
  exit 1
fi
RUNTIME_BUILD_ID="$SE_VERSION+$GIT_SHORT_SHA"

BUILD_INFO_PATH="$UNITY_PKG/Runtime/NativeRuntimeBuildInfo.g.cs"
cat >"$BUILD_INFO_PATH" <<EOF_BUILD_INFO
namespace Herki.ScriptingEngine
{

/// <summary>
/// Generated by build scripts to pin managed bindings to an exact native runtime build.
/// </summary>
internal static class NativeRuntimeBuildInfo
{
    public const string UnsetBuildId = "UNSET";
    public const string ExpectedBuildId = "$RUNTIME_BUILD_ID";
}

}
EOF_BUILD_INFO

"$ROOT_DIR/scripts/check-scripting-engine-runtime-layout.sh" --verify-exports

echo "Built scripting engine FFI"
echo "  target: $TARGET"
echo "  profile: $PROFILE"
echo "  source: $OUT_PATH"
echo "  destination: $DEST_DIR/$(basename "$OUT_PATH")"
echo "  runtime build id: $RUNTIME_BUILD_ID"
echo "  generated: $BUILD_INFO_PATH"
